#!/bin/bash

echo "🔧 HashPack Connection Troubleshooting Guide"
echo "============================================="

echo ""
echo "📱 Current Server Status:"
echo "   Local: http://localhost:5173/"
echo "   Network: http://192.168.1.3:5173/"
echo "   Auth Page: http://192.168.1.3:5173/auth"
echo ""

echo "🔍 Troubleshooting Steps:"
echo ""
echo "1. 🌐 Open Browser and Navigate to:"
echo "   http://192.168.1.3:5173/auth"
echo ""
echo "2. 🔧 Open Developer Tools (F12):"
echo "   - Go to Console tab"
echo "   - Look for any error messages"
echo ""
echo "3. 🧹 Clear Browser Data:"
echo "   - Press Ctrl+Shift+Delete (Windows/Linux)"
echo "   - Or Cmd+Shift+Delete (Mac)"
echo "   - Select 'All time' and clear everything"
echo ""
echo "4. 🔄 Alternative: Clear localStorage manually:"
echo "   - In Console, run: localStorage.clear()"
echo "   - Refresh the page"
echo ""
echo "5. 🔌 Check HashPack Extension:"
echo "   - Ensure HashPack extension is installed"
echo "   - Update to latest version if needed"
echo "   - Visit: https://www.hashpack.app/"
echo ""
echo "6. 🧪 Test in Incognito Mode:"
echo "   - Open incognito/private window"
echo "   - Navigate to: http://192.168.1.3:5173/auth"
echo "   - Try connecting HashPack"
echo ""
echo "7. 🔍 Check Console Logs:"
echo "   Look for these messages:"
echo "   ✅ '🔧 Initializing HashConnect with projectId: 9cb3860b32976358e227328e2b0a95a7'"
echo "   ✅ '🚀 Calling HashConnect.init()...'"
echo "   ✅ '✅ HashConnect initialized successfully'"
echo "   ❌ Any error messages with 'URI Missing' or similar"
echo ""
echo "8. 🛠️ Manual Test Commands (in Console):"
echo "   // Test HashConnect availability"
echo "   console.log('HashConnect available:', typeof window.hashconnect !== 'undefined');"
echo ""
echo "   // Test HashPack extension"
echo "   console.log('HashPack available:', typeof window.hashpack !== 'undefined');"
echo ""
echo "   // Clear all data"
echo "   localStorage.clear(); sessionStorage.clear();"
echo ""

echo "📋 Environment Check:"
if [ -f ".env" ]; then
    echo "   ✅ .env file exists"
    PROJECT_ID=$(grep VITE_HASHCONNECT_PROJECT_ID .env | cut -d'=' -f2)
    echo "   📄 Project ID: $PROJECT_ID"
else
    echo "   ❌ .env file missing"
fi

echo ""
echo "🚀 Quick Fixes:"
echo "   1. Restart server: pkill -f vite && npm run dev"
echo "   2. Clear browser cache completely"
echo "   3. Try different browser"
echo "   4. Check firewall/antivirus settings"
echo ""
echo "📞 If still not working:"
echo "   1. Screenshot the browser console errors"
echo "   2. Check HashPack extension version"
echo "   3. Try connecting from localhost:5173/auth instead"
